version: '3'

services:
  app:
    image: docker-logs-elk/springbootwebapp
    build:
      context: springbootwebapp
      dockerfile: Dockerfile
    depends_on:
      - logstash
    environment:
       - cluster.name=springboot
    ports:
      - 8888:8888
  filebeat:
    hostname: filebeat
    image: docker-logs-elk/filebeat:1.0.0
    build:
      context: filebeat
      dockerfile: Dockerfile
    volumes:
      # needed to access all docker logs (read only) :
     - "/var/lib/docker/containers:/usr/share/dockerlogs/data:ro"
      # needed to access additional informations about containers
     - "/var/run/docker.sock:/var/run/docker.sock"
    links:
       - logstash
  logstash:
    hostname: logstash
    build: ./logstash
    depends_on:
      - elasticsearch
    ports:
      - 5140:5140
  elasticsearch:
    hostname: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.2
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
  kibana:
    build: ./kibana
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
      
